import Vue from 'vue'
import Unicon from 'vue-unicons'

// Use https://antonreshetov.github.io/vue-unicons/ page for icon selection

import {
  // uniArrowToRight,
  // uniCommentAltExclamation,
  // uniFavoriteMonochrome,
  // uniFeedback,
  // uniHeart,
  // uniHeartAlt,
  // uniHistoryAlt,
  // uniLeftArrowToLeft,
  // uniPostcard,
  // uniQuestionCircle,
  // uniSearch,
  // uniShoppingCartAlt,
  // uniStar,
  // uniThumbsUp,
  uniArrowDown,
  uniArrowLeft,
  uniArrowRight,
  uniArrowUp,
  uniAt,
  uniClock,
  uniCommentMessage,
  uniDocumentLayoutLeft,
  uniEllipsisH,
  uniFacebook,
  uniHomeAlt,
  uniImages,
  uniInstagram,
  uniLinkedin,
  uniMapMarker,
  uniPause,
  uniPhone,
  uniPlay,
  uniStarMonochrome,
  uniStore,
  uniTwitter,
  uniUserSquare
} from 'vue-unicons/src/icons'

Unicon.add([
  // uniArrowToRight,
  // uniCommentAltExclamation,
  // uniFavoriteMonochrome,
  // uniFeedback,
  // uniHeart,
  // uniHeartAlt,
  // uniHistoryAlt,
  // uniLeftArrowToLeft,
  // uniPostcard,
  // uniQuestionCircle,
  // uniSearch,
  // uniShoppingCartAlt,
  // uniStar,
  // uniThumbsUp,
  uniArrowDown,
  uniArrowLeft,
  uniArrowRight,
  uniArrowUp,
  uniAt,
  uniClock,
  uniCommentMessage,
  uniDocumentLayoutLeft,
  uniEllipsisH,
  uniFacebook,
  uniHomeAlt,
  uniImages,
  uniInstagram,
  uniLinkedin,
  uniMapMarker,
  uniPause,
  uniPhone,
  uniPlay,
  uniStarMonochrome,
  uniStore,
  uniTwitter,
  uniUserSquare
])
Vue.use(Unicon)
